version: '3'

services: 

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /root/monitoring/uptime-kuma/data:/app/data
    ports:
      - 3003:3001  # <Host Port>:<Container Port>
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
